### PR TITLE
Fix infinite spinner on bookmarked location searches

### LINKED ISSUE #481: bookmarked "near location" searches not working
https://tsml-ui.code4recovery.org/tests/aasanjose.html#/?distance=5&search=sap+center&mode=location

### PR DESCRIPTION
**Pull request by pjaudiomv**
location mode required bounds to be loaded before geocoding could start, but bounds are only available after data loads, creating a deadlock.  I modified geocoding conditions to skip bounds requirement for location mode, breaking the circular dependency while preserving existing UI behavior

https://deploy-preview-482--tsml-ui.netlify.app/tests/aasanjose.html#/?distance=5&search=sap+center&mode=location

closes #481

### CODE REVIEW

**Comment by joshreisner** [comment]
thanks for looking at this! i like that the change is so simple, but i think we have to have the bounds unfortunately.

File: src/hooks/data.tsx [hunk 1]
```diff
@@ -31,11 +31,11 @@ export type Data = {
...
-    distance: Index[];
-    region: Index[];
-    time: Index[];
-    type: Index[];
-    weekday: Index[];
+    distance: any[];
+    region: any[];
+    time: any[];
+    type: any[];
+    weekday: any[];
```
Comment (joshreisner) [inline src/hooks/data.tsx]: do we need this typescript change?

Comment (pjaudiomv) [reply src/hooks/data.tsx]: No we don't!, I temporary changed it and forgot to put back. thanks

File: src/hooks/data.tsx [hunk 2]
```diff
@@ -173,54 +174,35 @@ export const DataProvider = ({
...
     }));
-  }, [latitude, longitude, data.meetings, settings.distance_unit]);
+  }, [calculateDistances, data.waitingForData]);
 
   return <DataContext.Provider value={data}>{children}</DataContext.Provider>;
 };
+
+export const DataProvider = (props: PropsWithChildren<{ google?: string; src?: string; timezone?: string }>) => {
+  return (
+    <LocationProvider>
```
Comment (joshreisner) [inline src/hooks/data.tsx]: thanks so much for working on this! i'm going to approve and merge because this fixes the issue but i think in the next update i might want to move this LocationProvider call to the TsmlUi component unless there's a specific reason not to

**Review by joshreisner — APPROVED** [review]
